### ISSUE TITLE
No license specified for this project

### ISSUE THREAD

**Issue by desplesda** [ryanslikesocool/Unity-Card-UI#2]
Thanks for this awesome project!

Currently, there's no license specified, which (under US copyright law) means that nobody apart from you have permission to use it. If you'd like others to have permission to use it, you should probably add a license like the MIT license (which means that everyone is allowed to use it, as long as they credit you, and don't expect you to provide technical support.)

If you'd like, I can file a pull request that adds it?

**Comment by ryanslikesocool** [comment]
Thank you for the heads up!  I’ve gone and added a license and I’ll be sure to add one for future projects.
